---
hrr:
  Unit_HRR_CaptureSmoke:
    <<: *level_2
    disabled:
      targets: [amd_linux, amd_windows, amd_wsl, nvidia_linux, nvidia_windows]
      reason: "Needs to be re-triaged AIRUNTIME-2744"
    tags: [smoke, capture]
  Unit_HRR_CaptureSmoke_Direct:
    <<: *level_2
    disabled:
      targets: [amd_linux, amd_windows, amd_wsl, nvidia_linux, nvidia_windows]
      reason: "Needs to be re-triaged AIRUNTIME-2744"
    tags: [direct, smoke]
